openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
paths:
  /auth/direcciones:
    post:
      tags:
      - direccion-controller
      operationId: create_1
      parameters:
      - name: idUser
        in: query
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DireccionRequest'
        required: true
      responses:
        '201':
          description: Created
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DireccionResponse'
  /auth/direcciones/user/{idUser}:
    get:
      tags:
      - direccion-controller
      operationId: getByUser_1
      parameters:
      - name: idUser
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DireccionResponse'
components:
  schemas:
    UserUpdateRequest:
      type: object
      properties:
        currentPassword:
          type: string
        newUsername:
          type: string
        newEmail:
          type: string
    UserResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        email:
          type: string
        fechaNacimiento:
          type: string
          format: date
        telefono:
          type: string
    TipoProductoRequest:
      required:
      - tipo
      type: object
      properties:
        tipo:
          type: string
        descripcion:
          type: string
    TipoProductoResponse:
      type: object
      properties:
        idTipoProducto:
          type: integer
          format: int64
        tipo:
          type: string
        descripcion:
          type: string
    Ropa:
      type: object
      properties:
        idRopa:
          type: integer
          format: int64
        nombre:
          type: string
        precio:
          type: number
          format: double
    ProductoRequest:
      required:
      - cantidad
      - cantidadPuntos
      - costo
      - descripcion
      - idTipoProducto
      - nombre
      - precio
      type: object
      properties:
        nombre:
          type: string
        descripcion:
          type: string
        precio:
          type: number
        costo:
          type: number
        cantidad:
          type: integer
          format: int32
        imagen:
          type: string
        cantidadPuntos:
          type: integer
          format: int32
        idTipoProducto:
          type: integer
          format: int64
    Links:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Link'
    ProductoResponse:
      type: object
      properties:
        idProducto:
          type: integer
          format: int64
        nombre:
          type: string
        descripcion:
          type: string
        precio:
          type: number
        costo:
          type: number
        cantidad:
          type: integer
          format: int32
        imagen:
          type: string
        cantidadPuntos:
          type: integer
          format: int32
        idTipoProducto:
          type: integer
          format: int64
        nombreTipo:
          type: string
        fechaCreacion:
          type: string
          format: date-time
        fechaActualizacion:
          type: string
          format: date-time
        _links:
          $ref: '#/components/schemas/Links'
    Parametro:
      type: object
      properties:
        idParametro:
          type: integer
          format: int64
        clave:
          type: string
        valor:
          type: string
        descripcion:
          type: string
    CarritoItemRequest:
      required:
      - idCarrito
      - idProducto
      type: object
      properties:
        idCarrito:
          type: integer
          format: int64
        idProducto:
          type: integer
          format: int64
        cantidad:
          type: integer
          format: int32
    CarritoItemResponse:
      type: object
      properties:
        idCarritoItem:
          type: integer
          format: int64
        idCarrito:
          type: integer
          format: int64
        idProducto:
          type: integer
          format: int64
        cantidad:
          type: integer
          format: int32
        producto:
          $ref: '#/components/schemas/ProductoResponse'
    ResenaRequest:
      required:
      - idProducto
      - idUser
      type: object
      properties:
        idUser:
          type: integer
          format: int64
        idProducto:
          type: integer
          format: int64
        comentario:
          type: string
        rating:
          type: string
          enum:
          - ZERO
          - HALF
          - ONE
          - ONE_HALF
          - TWO
          - TWO_HALF
          - THREE
          - THREE_HALF
          - FOUR
          - FOUR_HALF
          - FIVE
    ResenaResponse:
      type: object
      properties:
        idResena:
          type: integer
          format: int64
        username:
          type: string
        productoNombre:
          type: string
        comentario:
          type: string
        fecha:
          type: string
          format: date-time
        rating:
          type: string
          enum:
          - ZERO
          - HALF
          - ONE
          - ONE_HALF
          - TWO
          - TWO_HALF
          - THREE
          - THREE_HALF
          - FOUR
          - FOUR_HALF
          - FIVE
        _links:
          $ref: '#/components/schemas/Links'
    RegisterRequest:
      required:
      - direccion
      - dui
      - email
      - fechaNacimiento
      - password
      - primerApellido
      - primerNombre
      - telefono
      - username
      type: object
      properties:
        username:
          maxLength: 20
          minLength: 5
          type: string
        password:
          maxLength: 2147483647
          minLength: 8
          type: string
        email:
          type: string
        primerNombre:
          type: string
        segundoNombre:
          type: string
        primerApellido:
          type: string
        segundoApellido:
          type: string
        fechaNacimiento:
          type: string
          format: date
        telefono:
          type: string
        dui:
          type: string
        direccion:
          type: string
    PagoRequest:
      type: object
      properties:
        usuario:
          $ref: '#/components/schemas/User'
        detallesPago:
          type: string
    Role:
      type: object
      properties:
        idRol:
          type: integer
          format: int64
        name:
          type: string
    User:
      type: object
      properties:
        idUser:
          type: integer
          format: int64
        role:
          $ref: '#/components/schemas/Role'
        primerNombre:
          type: string
        segundoNombre:
          type: string
        primerApellido:
          type: string
        segundoApellido:
          type: string
        fechaNacimiento:
          type: string
          format: date
        email:
          type: string
        username:
          type: string
        password:
          type: string
        telefono:
          type: string
        direccion:
          type: string
        puntos:
          type: integer
          format: int32
        dui:
          type: string
    PedidoResponse:
      type: object
      properties:
        idPedido:
          type: integer
          format: int64
        fechaInicio:
          type: string
          format: date-time
        fechaFinal:
          type: string
          format: date-time
        total:
          type: number
        puntosTotales:
          type: integer
          format: int32
        idCarrito:
          type: integer
          format: int64
        tipoPago:
          type: string
          enum:
          - TARJETA_CREDITO
          - PAYPAL
          - EFECTIVO
          - TRANSFERENCIA_BANCARIA
        estado:
          type: string
          enum:
          - CARRITO
          - PENDIENTE
          - PAGADO
          - EN_PROCESO
          - ENVIADO
          - ENTREGADO
          - CANCELADO
        idDireccion:
          type: integer
          format: int64
        aliasDireccion:
          type: string
        calleDireccion:
          type: string
        ciudadDireccion:
          type: string
        departamentoDireccion:
          type: string
        _links:
          $ref: '#/components/schemas/Links'
    PedidoRequest:
      required:
      - idCarrito
      - tipoPago
      type: object
      properties:
        idCarrito:
          type: integer
          format: int64
        tipoPago:
          type: string
          enum:
          - TARJETA_CREDITO
          - PAYPAL
          - EFECTIVO
          - TRANSFERENCIA_BANCARIA
        cuponCodigo:
          type: string
        idDireccion:
          type: integer
          format: int64
    LoginRequest:
      required:
      - password
      - username
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    DireccionRequest:
      type: object
      properties:
        alias:
          type: string
        calle:
          type: string
        ciudad:
          type: string
        departamento:
          type: string
        latitud:
          type: number
          format: double
        longitud:
          type: number
          format: double
    DireccionResponse:
      type: object
      properties:
        idDireccion:
          type: integer
          format: int64
        alias:
          type: string
        calle:
          type: string
        ciudad:
          type: string
        departamento:
          type: string
        latitud:
          type: number
          format: double
        longitud:
          type: number
          format: double
    Pageable:
      type: object
      properties:
        page:
          minimum: 0
          type: integer
          format: int32
        size:
          minimum: 1
          type: integer
          format: int32
        sort:
          type: array
          items:
            type: string
    PageMetadata:
      type: object
      properties:
        size:
          type: integer
          format: int64
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int64
        number:
          type: integer
          format: int64
    PagedModelResenaResponse:
      type: object
      properties:
        _embedded:
          type: object
          properties:
            resenaResponseList:
              type: array
              items:
                $ref: '#/components/schemas/ResenaResponse'
        _links:
          $ref: '#/components/schemas/Links'
        page:
          $ref: '#/components/schemas/PageMetadata'
    CollectionModelProductoResponse:
      type: object
      properties:
        _embedded:
          type: object
          properties:
            productoResponseList:
              type: array
              items:
                $ref: '#/components/schemas/ProductoResponse'
        _links:
          $ref: '#/components/schemas/Links'
    PagedModelProductoResponse:
      type: object
      properties:
        _embedded:
          type: object
          properties:
            productoResponseList:
              type: array
              items:
                $ref: '#/components/schemas/ProductoResponse'
        _links:
          $ref: '#/components/schemas/Links'
        page:
          $ref: '#/components/schemas/PageMetadata'
    PagedResourcesAssemblerPedido:
      type: object
      properties:
        forceFirstAndLastRels:
          type: boolean
          writeOnly: true
    PagedModelPedidoResponse:
      type: object
      properties:
        _embedded:
          type: object
          properties:
            pedidoResponseList:
              type: array
              items:
                $ref: '#/components/schemas/PedidoResponse'
        _links:
          $ref: '#/components/schemas/Links'
        page:
          $ref: '#/components/schemas/PageMetadata'
    NotificacionResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        mensaje:
          type: string
        fechaEnvio:
          type: string
          format: date-time
        estado:
          type: string
        pedidoId:
          type: integer
          format: int64
    PagedResourcesAssemblerHistorialPuntos:
      type: object
      properties:
        forceFirstAndLastRels:
          type: boolean
          writeOnly: true
    HistorialPuntosResponse:
      type: object
      properties:
        idHistorialPuntos:
          type: integer
          format: int64
        idUser:
          type: integer
          format: int64
        idPedido:
          type: integer
          format: int64
        fecha:
          type: string
          format: date-time
        cantidadAnterior:
          type: integer
          format: int32
        cantidadNueva:
          type: integer
          format: int32
        _links:
          $ref: '#/components/schemas/Links'
    PagedModelHistorialPuntosResponse:
      type: object
      properties:
        _embedded:
          type: object
          properties:
            historialPuntosResponseList:
              type: array
              items:
                $ref: '#/components/schemas/HistorialPuntosResponse'
        _links:
          $ref: '#/components/schemas/Links'
        page:
          $ref: '#/components/schemas/PageMetadata'
    PagedResourcesAssemblerHistorialPedido:
      type: object
      properties:
        forceFirstAndLastRels:
          type: boolean
          writeOnly: true
    HistorialPedidoResponse:
      type: object
      properties:
        idHistorialPedido:
          type: integer
          format: int64
        idPedido:
          type: integer
          format: int64
        idUser:
          type: integer
          format: int64
        estado:
          type: string
          enum:
          - CARRITO
          - PENDIENTE
          - PAGADO
          - EN_PROCESO
          - ENVIADO
          - ENTREGADO
          - CANCELADO
        fecha:
          type: string
          format: date-time
        descripcion:
          type: string
        _links:
          $ref: '#/components/schemas/Links'
    PagedModelHistorialPedidoResponse:
      type: object
      properties:
        _embedded:
          type: object
          properties:
            historialPedidoResponseList:
              type: array
              items:
                $ref: '#/components/schemas/HistorialPedidoResponse'
        _links:
          $ref: '#/components/schemas/Links'
        page:
          $ref: '#/components/schemas/PageMetadata'
    CarritoResponse:
      type: object
      properties:
        idCarrito:
          type: integer
          format: int64
        idUser:
          type: integer
          format: int64
        fechaCreacion:
          type: string
          format: date-time
        items:
          type: array
          items:
            $ref: '#/components/schemas/CarritoItemResponse'
    Link:
      type: object
      properties:
        href:
          type: string
        hreflang:
          type: string
        title:
          type: string
        type:
          type: string
        deprecation:
          type: string
        profile:
          type: string
        name:
          type: string
        templated:
          type: boolean
